name: example_app
description: "flutter_scene example project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-82.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_scene:
    path: ../../
  #flutter_scene_importer: ^0.9.2-0
  flutter_scene_importer:
    path: ../../importer
  native_assets_cli: '>=0.13.0 <0.14.0'
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/little_paris_eiffel_tower.png
    - assets/little_paris_eiffel_tower_irradiance.png
    # Imported models.
    - build/models/
